kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: idtolu-images-server
  namespace: testbed-ns
  labels:
    k8s-app: idtolu-images-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-ext4
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: idtolu-images-server
  namespace: testbed-ns
  labels:
    k8s-app: idtolu-images-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: idtolu-images-server
  template:
    metadata:
      name: idtolu-images-server
      labels:
        k8s-app: idtolu-images-server
    spec:
      volumes:
        - name: idtolu-images
          persistentVolumeClaim:
            claimName: idtolu-images-server
      containers:
        - name: idtolu-images-server
          image: registry.idtolu.net/testbed/idtolu-images-server:<IMAGE_TAG>
          ports:
            - containerPort: 1995
          env:
            - name: ROOT_PATH_IMAGES
              value: /srv/images
          volumeMounts:
            - name: idtolu-images
              mountPath: /srv/images
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: idtolu-images-server
  namespace: testbed-ns
  labels:
    k8s-app: idtolu-images-server
spec:
  ports:
    - name: images-server
      protocol: TCP
      port: 1995
      targetPort: 1995
      nodePort: 30995
  selector:
    k8s-app: idtolu-images-server
  type: NodePort